# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        args: [--unsafe]
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: (^|/)\.gitignore$
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
      - id: requirements-txt-fixer
        files: requirements.*\.in$
      - id: trailing-whitespace
        exclude: (^|/)\.gitignore$
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        language: system
        types_or: [cython, pyi, python]
        require_serial: true
